version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: sh ./dev-start.sh
    environment:
      PORT: 3000
      NODE_ENV: "development"
      DB_USERNAME: test
      DB_PASSWORD: 1234
      DB_DATABASE: socialBlog
      DB_HOSTNAME: db
      DB_DIALECT: mysql
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: socialBlog
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 10s
      timeout: 2s
      retries: 10
volumes:
  db_data:
